services:
  back-end:
    build:
      context: .
      args:
        PORT: ${PORT:-3000}
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3000}/"]
      interval: 5s
      timeout: 5s
      retries: 5
